baseurl = "https://master.d21605t5ng2nsa.amplifyapp.com"
theme = "../.."
builddrafts = true
# canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Vrindha Arun Kumar"
title = "  Thoughts of Vrindha"
disqusshortname = ""
pluralizelisttitles = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "My Blog"
copyright = "Copyright © 2020-{year} Vrindha Arun Kumar"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/tree1.jpg"
faviconfile = "img/tree.jpg"
highlightjs = true
progressively = true
share = true
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
latestpostcount = 5
# github = "example"
# email = "you@example.com"
# linkedin = "john-example-aa80ue8è"
# twitter = "example"
# facebook = "facebook_id"
# instagram = "instagram_id"
# untappd = "untappd_id"
# itch_io = "itch_io_id"
# social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName/tree/master"
small_banner_logo = false

# [params.utteranc]
# enable = true
# repo = "mtn/cocoa-eh-hugo-theme"
# issueTerm = "title"
